// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktjpnycyzyohsrsgbzbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0anBueWN5enlvaHNyc2diemJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNDQzMzQsImV4cCI6MjA2MTgyMDMzNH0.JA80_zKhq4Eyjx6qhh7rjYFm_b10MJk6pPkIyBZPHA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);